'use strict';

const ICON = '';
const LOCAL_DEVTOOLS_ADDRESS = '127.0.0.1';
const DEFAULT_SINK_WAIT_MS = 10000;
const STATUS_SINK_WAIT_MS = 1800;
const DEFAULT_CDP_TIMEOUT_MS = 5000;
const DEFAULT_BROWSER_START_TIMEOUT_MS = 12000;
const PROFILE_VERSION = 4;
const CHROMIUM_LAUNCH_CONFIG_VERSION = 1;
const MAX_AVAHI_OUTPUT_BYTES = 256 * 1024;
const MAX_CDP_HTTP_RESPONSE_BYTES = 1024 * 1024;
const MAX_CDP_WS_MESSAGE_BYTES = 1024 * 1024;
const MAX_SINKS = 64;
const MAX_SINK_NAME_CHARS = 160;
const MAX_SINK_ID_CHARS = 256;
const MAX_TERMINAL_TEXT_CHARS = 1000;
const DEFAULT_LOCK_TIMEOUT_MS = 30000;
const LOCK_STALE_MS = 120000;
const LOCK_RETRY_MS = 50;
// Matches C0 controls (U+0000-U+001F), DEL/C1 controls (U+007F-U+009F),
// and Unicode bidi override/isolate controls (U+202A-U+202E, U+2066-U+2069).
const CONTROL_OR_BIDI_PATTERN = /[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/u;

module.exports = {
  ICON,
  LOCAL_DEVTOOLS_ADDRESS,
  DEFAULT_SINK_WAIT_MS,
  STATUS_SINK_WAIT_MS,
  DEFAULT_CDP_TIMEOUT_MS,
  DEFAULT_BROWSER_START_TIMEOUT_MS,
  PROFILE_VERSION,
  CHROMIUM_LAUNCH_CONFIG_VERSION,
  MAX_AVAHI_OUTPUT_BYTES,
  MAX_CDP_HTTP_RESPONSE_BYTES,
  MAX_CDP_WS_MESSAGE_BYTES,
  MAX_SINKS,
  MAX_SINK_NAME_CHARS,
  MAX_SINK_ID_CHARS,
  MAX_TERMINAL_TEXT_CHARS,
  DEFAULT_LOCK_TIMEOUT_MS,
  LOCK_STALE_MS,
  LOCK_RETRY_MS,
  CONTROL_OR_BIDI_PATTERN,
};
